version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:9753
    volumes:
      - .:/app
    networks:
      - bmg

networks:
  bmg:
    driver: bridge
